---
title: "Untitled"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
KnitPost <- function(site.path = "~/Dropbox/Websites/hugo-blog/", rmd.file = NULL, categories = NULL, tags = NULL, tags.eq.cats = TRUE, rm.output.text = FALSE) {
  if(!'package:knitr' %in% search()) library('knitr')
wdX <- getwd()
  
  if(is.null(rmd.file)) stop("need to provide rmd.file biatch!")  
  on.exit(setwd(wdX))
  
  setwd(site.path)
  ## Blog-specific directories.  This will depend on how you organize your blog.
  # site.path <- site.path # directory of jekyll blog (including trailing slash)
  rmd.path <- paste0(site.path, "_Rmd") # directory where your Rmd-files reside (relative to base)
  fig.dir <- "statis/img/" # directory to save figures
  posts.path <- paste0(site.path, "_posts/") # directory for converted markdown files
  cache.path <- paste0(site.path, "_cache") # necessary for plots
  
  # render_jekyll()
  opts_knit$set(base.url = '/', base.dir = site.path)
  opts_chunk$set(fig.path=fig.dir, fig.width=8.5, fig.height=5.25, dev='png', cache=F, 
                 warning=F, message=F, cache.path=cache.path, tidy=F, dpi = 70)   
  

  setwd(site.path) # setwd to base
  

  corresponding.md.file <- paste0(posts.path, "/", basename(gsub(pattern = "\\.Rmd$", replacement = ".md", x = rmd.file)))
 
  #knitr!!
       out.file <- knit(as.character(rmd.file), 
                      output = as.character(corresponding.md.file),
                      envir = parent.frame(), 
                      quiet = T)
      message(paste0("KnitPost(): ", rmd.file))
      
      #fix heading to jekyll format
      #add layout post      
      x <- readLines(corresponding.md.file)
      x <- c(x[1], "layout: post", x[2:length(x)])
   
      #fix date format
      dl <- grep("date:", x)
      dln <- x[dl]

      dln <- gsub("date:","", dln)
            y <- sapply(strsplit(as.character(dln), "-",fixed=T), "[[", 1)
            y <- gsub(" ","", y)
             m <- sapply(strsplit(as.character(dln), "-",fixed=T), "[[", 2)
            m <- gsub(" ","", m)
            d <- sapply(strsplit(as.character(dln), "-",fixed=T), "[[", 3)
            d <- gsub(" ","", d)

            dln <- paste(d, m, y, sep = "-")
            dln <- gsub('"',"", dln)
            dln <- gsub(' ',"", dln)
            x[dl] <- paste("date:", dln)    

            #remove output:
            x <- x[-grep("output:", x)]   
             
            #remove md_document:
            x <- x[-grep("md_document:", x)]   
            
            #remove variant: markdown_github
            x <- x[-grep("variant: markdown_github", x)]   
          
              #remove output:
            x <- x[-grep("author:", x)]   
            
      #put it together as a file         
      cat(x, file = corresponding.md.file, sep="\n")
      
      #change name to include date
     
      nn <- paste(y, m , d, basename(corresponding.md.file), sep = "-")
      nn <- gsub('"',"", nn)
      #replace spaces with _
      nn <- gsub(" ","_", nn)
      
      file.rename(from = corresponding.md.file, to = file.path(posts.path, nn))

      unlink(list.files(path = "~/Dropbox/Websites/Blog/bioacoustics_in_R/_Rmd/", pattern = "\\.wav$"))      

      setwd(wdX)
      }

```

```{r, eval=F}
# 
# #Detecting_signals_with_monitoR
  KnitPost(site.path = "~/Dropbox/Websites/hugo-blog/", rmd.file =  "~/Dropbox/Websites/hugo-blog/_Rmd/Create dynamic spectro in R.Rmd", categories = "spectrograms, visualization", rm.output.text = F)

```


```{r, eval = FALSE}

blogdown::serve_site()

```


```{r}
remotes::install_github("maRce10/baRulho")

library(rmarkdown)

rmds <- list.files(path = "./_Rmd", pattern = "Rmd$", full.names = T)

for(i in rmds)
try(rmarkdown::render(i, hugodown::md_document(), output_dir = "./content/post"), silent = TRUE)

  
render("./_Rmd/Create dynamic spectro in R.Rmd", hugodown::md_document(), output_dir = "./content/post")

render("./_Rmd/barulho.Rmd", hugodown::md_document(), output_dir = "./content/post")

render("./_Rmd/Download a single recording for each species in a site from Xeno-Canto.Rmd", hugodown::md_document(), output_dir = "./content/post")


render("./_Rmd/Editing wave objects from extended selection tables.Rmd", hugodown::md_document(), output_dir = "./content/post")

render("./_Rmd/Choosing the right method for measuring acoustic signal structure.Rmd", hugodown::md_document(), output_dir = "./content/post")


```

